# 当master有代码提交或者有pr时，自动build gitbook，并覆盖git@github.com:zeromicro/go-zero.git仓库中内容
# 以实现自动发布文档

name: Document Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build&publish
        run: ./build.sh ${{ secrets.ACCESSTOKEN }}
        shell: bash
